name: Compile SCSS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Sass
        uses: sass/dart-sass@v1

      - name: Compile SCSS
        run: sass scss/styles.scss css/processed.css

      - name: Commit CSS
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-compile SCSS"
